services:
  bot:
    build: .
    container_name: hr_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: hr_db
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: